dist: trusty
language: c++
sudo: required

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
    - valgrind
    - verilog

before_install:
  - export COREIRCONFIG="g++-4.9";
  - wget https://github.com/rdaly525/coreir/releases/download/v0.0.26/coreir.tar.gz
  - tar -xvzf coreir.tar.gz
  - cd release
  - sudo make install -j
  - cd ..
  - ls release/lib
  - cmake -DCMAKE_C_COMPILER=/usr/bin/gcc-4.9 -DCMAKE_CXX_COMPILER=/usr/bin/g++-4.9 .
  - make -j

script:
 - ./run_travis.sh

compiler:
  - gcc

os:
- linux